[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_HUGGING_FACE_TOKEN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200